### ISSUE TITLE
libnet_get_hwaddr(): socket: Permission denied

### ISSUE THREAD

**Issue by lxjin81** [libnet/libnet#100]
when i call this method , get this error :
libnet_get_hwaddr(): socket: Permission denied.
i,m  already use the root account to run.
and my env. is linux chroot on android phone:
Linux kali 3.10.40-lasyka+ #30 SMP PREEMPT Sat Sep 29 19:40:50 CST 2018 armv7l GNU/Linux

**Comment by troglobit** [comment]
My guess is that your phone is locked down with some sort of framework like apparmor that blocks network access, despite your being root.  A quick google gives the following suggestion from Stackoverflow: https://stackoverflow.com/questions/36451444/what-can-cause-a-socket-permission-denied-error

So, this is likely not a problem with libnet.

**Comment by lxjin81** [comment]
Is it is not a libnet problem.
