### ISSUE TITLE
Moving Nemesis under the libnet org. umbrella

### ISSUE THREAD

**Issue by troglobit** [libnet/libnet#110]
I've been considering moving the https://github.com/troglobit/nemesis/ project in under the libnet org. umbrella.  What do you think about that, @sam-github ?

**Comment by sam-github** [comment]
Go for it, seems a natural fit.

**Comment by troglobit** [comment]
Thanks Sam!  Thought it best to check with you first :)

Done, looks much better this way -- https://github.com/libnet/nemesis
