### ISSUE TITLE
Release tarball doesn't contain COPYING file

### ISSUE THREAD

**Issue by robert-scheck** [libnet/libnet#114]
Unfortunately, the release tarball and the release zip file at https://github.com/libnet/libnet/releases/tag/v1.2 do not offer any COPYING file…I guess that's not intended. I would appreciate it, if the next release could contain it.

**Comment by troglobit** [comment]
Usually only GNU projects carry the name COPYING for their license, this is a BSD-style licensed project and we've used the name LICENSE for the project for quite some time, as do many many other projects.  We will likely not change the name.

The file LICENSE is available in both the .tar.gz and .zip archives in your referenced URL.

**Comment by troglobit** [comment]
s/GNU/GPL:ed/ ... obvs.

**Comment by robert-scheck** [comment]
Thank you for the pointer...coming from v1.1 I just noticed that `COPYING` is gone, `LICENSE` is absolutely fine indeed.
