### ISSUE TITLE
Library soname bump from libnet.so.1 to libnet.so.9

### ISSUE THREAD

**Issue by robert-scheck** [libnet/libnet#115]
Is it intended that the library soname was bumped from libnet.so.1 (libnet 1.1.x) to libnet.so.9 (libnet 1.2)? Based on [ChangeLog](https://github.com/libnet/libnet/blob/master/ChangeLog.md), I didn't see a reason for one (or multiple) ABI bumps. What am I overlooking?

**Comment by troglobit** [comment]
A lot of things has happened since the 1.1.0 release.  The 1.1 and 1.2 releases are *not* ABI compatible.  Most of this happened before I jumped in as co-maintainer.  For details, see

https://github.com/libnet/libnet/blob/master/src/Makefile.am

**Comment by sam-github** [comment]
https://github.com/libnet/libnet/blob/master/src/Makefile.am#L90-L95 shows the history, and the rules are non-obvious so I pasted them into the Makefile. I checked with at least one downstream packager (I think it was for one of the BSDs), and was assured I was getting it right.

**Comment by robert-scheck** [comment]
When looking to my old Fedora builds, I wonder where this soname documentation in the Makefile actually comes from, because:

  * libnet 1.1.3 → libnet.so.1.5.0
  * libnet 1.1.4 → libnet.so.1.5.0
  * libnet 1.1.5 → libnet.so.1.6.0
  * libnet 1.1.6 → libnet.so.1.7.0
  * libnet 1.2.0 → libnet.so.9.0.0

Thus libnet 1.1.3 to 1.1.6 actually claimed ABI compatibility (and that's what I would agree with).

**Comment by troglobit** [comment]
So it's probably my fault then, when I stepped it for the 1.2.0 release. Sorry about that, it's not the first time I stumble on the libtool rules :-/

**Comment by sam-github** [comment]
As far as I can tell, @troglobit did exactly what the rules from autobook and the libtool docs said to. The `.so.9` surprises me, too, but the relationship between the `libtool -version-info` and the filename does not appear to be a simple 1-1.

**Comment by troglobit** [comment]
Not sure really how to proceed with this issue. It's obviously too late to fix this, so I'm leaning towards closing.  But maybe we should set up a GitHub Discussions forum (now that it's available), for future questions like this?

**Comment by robert-scheck** [comment]
I've currently on my list to check with `abi-compliance-checker` the actual incompatibilities, because for downstreams (e.g. Linux distributions) it still matters to avoid unnecessary mass-rebuilds.

**Comment by troglobit** [comment]
@robert-scheck OK, that's a good idea.  I just realized I confused things quite a bit above, it's the 1.0.x and 1.1.x release series that are incompatible.  The 1.2.x series should actually be ABI compatible with 1.1.x.

Also, I tracked down the original ABI bump, from 2013, here 2010b4da9ccee3662a9bfdd6e761c2e91fc4f5f2.  I guess I kept it as-is for the 1.2 release because it had been such a long time.

**Comment by robert-scheck** [comment]
Here we go (created using `abi-compliance-checker`):

  * [1.1.3 → 1.1.4 (gzip compressed HTML)](https://github.com/libnet/libnet/files/5759861/1.1.3_to_1.1.4.html.gz)
  * [1.1.4 → 1.1.5 (gzip compressed HTML)](https://github.com/libnet/libnet/files/5759862/1.1.4_to_1.1.5.html.gz)
  * [1.1.5 → 1.1.6 (gzip compressed HTML)](https://github.com/libnet/libnet/files/5759863/1.1.5_to_1.1.6.html.gz)
  * [1.1.6 → 1.2 (gzip compressed HTML)](https://github.com/libnet/libnet/files/5759864/1.1.6_to_1.2.html.gz)

Plaintext dump of the beginning of the last report:

```
API compatibility report for the libnet.so object between 1.1.6 and 1.2 versions
                                   on x86_64

   Binary
   Compatibility Source
   Compatibility

Test Info
     __________________________________________________________________

   Module Name libnet
   Version #1  1.1.6
   Version #2  1.2
      Arch     x86_64
   GCC Version 4.8.5
     Subject   Binary Compatibility

Test Results
     __________________________________________________________________

    Total Header Files   10
    Total Source Files   49
       Total Objects     1
   Total Symbols / Types 171 / 35
       Compatibility     99.4%

Problem Summary
     __________________________________________________________________

                             Severity Count
              Added Symbols  -        1
             Removed Symbols High     1
   Problems with
   Data Types                High     0
                             Medium   0
             Low             5
   Problems with
   Symbols                   High     0
                             Medium   0
             Low             6
   Problems with
   Constants Low             0
```

Sources for reports above (created using `abi-dumper`):

  * [gzip compressed ABI dump of libnet-1.1.3](https://github.com/libnet/libnet/files/5759867/libnet-1.1.3.abi.gz)
  * [gzip compressed ABI dump of libnet-1.1.4](https://github.com/libnet/libnet/files/5759868/libnet-1.1.4.abi.gz)
  * [gzip compressed ABI dump of libnet-1.1.5](https://github.com/libnet/libnet/files/5759869/libnet-1.1.5.abi.gz)
  * [gzip compressed ABI dump of libnet-1.1.6](https://github.com/libnet/libnet/files/5759870/libnet-1.1.6.abi.gz)
  * [gzip compressed ABI dump of libnet-1.2](https://github.com/libnet/libnet/files/5759871/libnet-1.2.abi.gz)

**Comment by troglobit** [comment]
Thanks.  This confirms the mention in Makefile.am, referenced above.

> `# 1.2   is 9:0:0 -> new APIs, removed __libnet_print_vers (internal, should not have been used, but linkable)`

Still unsure how to proceed with this issue.  The release is out there, and has been for some time, so we'll probably not change the ABI version.  So I propose closing it.
