### ISSUE TITLE
[question] There is no problem to add the libnet to the Conan package manager?

### ISSUE THREAD

**Issue by ivalery111** [libnet/libnet#127]
Hey @troglobit ,

I want to add a [recipe](https://github.com/conan-io/conan-center-index/pull/5977) for the libnet to the Conan. I checked out the license and I do not see any problem.

Is ok for you?:)

**Comment by troglobit** [comment]
Of course, go right ahead! ❤️

**Comment by ivalery111** [comment]
The conan recipe for libnet was merged successfully. I'll prepare the PR to update the `Building` part in README.md
