### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [libnet/libnet#130]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by ivalery111** [comment]
Hey Thomasz,

I saw you also requested to flush the progress in the CRIU project.

It’s seems like there is a some sense behind of this:)

Interesting for me if yes or not:)

Thank you.

**Comment by troglobit** [comment]
Yes, I've actually been meaning to for some time now, but other more pressing projects have taken priority so far, unfortunately.  I'm on vacation right now and working on SMCRoute and Qeneth, but I've moved libnet relase to the place 4 on my own Kanban.  Hopefully I can get to it before vacation is over.

@ivalery111 btw, I realize now I never checked the resulting docs for your lldp contribution.  Is it all up to snuff? The autogenerated docs are at https://codedocs.xyz/libnet/libnet/ and going through that is one of the outstanding items in the release process, so anyone that can help audit that would be much appreciated.

**Comment by ivalery111** [comment]
I will try to check out the docs on weekend. I do not want to to be a blocker for a new release.

**Comment by ivalery111** [comment]
I checked out the autogenerated docs. IMHO it's looks good.

Also, when I added new functionality, I tried to keep the project's style, so, are fields, functions were commented respectively.

**Comment by troglobit** [comment]
Very good, thank yoy @ivalery111 :heart:

**Comment by kloczek** [comment]
> Hey @kloczek
> 
> I saw you also requested to flush the progress in the CRIU project.
> 
> It’s seems like there is a some sense behind of this:)
> 
> Interesting for me if yes or not:)

I understand and there is no any hidden sense of those changes.
I'm packaging stuff and as I see some some significant set of already commit changes I have two choices:
- integrate at least some patches in my build procedure basing mostly on commits comments
- as for make new release and receive more or less clear signal are those changes ready to be released or to hold any of my attempts to integrate those changes in my build procedures.

Sometimes I see additionally that some changes are additionally without flushing them as new release.
I know that many maintainers are holding some changes be afraid of some negative side effects. In case of software there is no such thing like negative impact of new release because IMO only negative impact is when some well known fixes are held.
More frequent smaller chunks of changes have additionally two side effects:
- new release focuses attention of people like me to test more or less that new release
- more frequent changes as well encourages some people to push on changes to the maintainers

In case of spotted bugs only matters how quickly fouled issue is sorted out :)

If you will look closer on my github activity you can find that I'm using such humble questions sometimes few times every week and it allows me indirectly asses state of the project as well :P
From that point of view you can blame me as well for appearance of new version of some software :P

**Comment by ivalery111** [comment]
Fine, thank you very much for detailed explanation:)

**Comment by beni-sandu** [comment]
Hey folks, any update on this front?

Last release was in 2019, so it is getting quite far away from that, and I think prolonging will make it harder to do it.

Although I have used libnet in a few of my projects, I am not familiar with the actual codebase, so no idea if there are any issues there that would make a new release difficult, but I can try to help if needed.

Thanks,
Beni

**Comment by troglobit** [comment]
Thank you for the gentle reminder, I'll see what I can do.  There are no open blockers right now, it's just the release work and testing.

**Comment by ivalery111** [comment]
> Thank you for the gentle reminder, I'll see what I can do. There are no open blockers right now, it's just the release work and testing.

Please let me know if you need some help.

**Comment by troglobit** [comment]
Well, if you're up to it. Any of you, the most time consuming part is updating the ChangeLog.md with all the major (user visible) changes.

I prefer to have this is in a human friendly format rather than just `git log --pretty="- %s" > ChangeLog.md` because most devs, including myself, are incapable of writing useful summaries in their commits.

Usually this entails digging thru any reported issues, matching that to commit message and figuring out how (and if) it affects users of the library.  Most of it is monkey work and quite straight forward, but there often is something that you end up test once again just to make sure the review didn't miss anything and we accidentally cause regressions.

**Comment by troglobit** [comment]
OK, I've [updated the ChangeLog](https://github.com/libnet/libnet/blob/master/ChangeLog.md) now, any comments/fixes would be really appreciated!

**Comment by beni-sandu** [comment]
ChangeLog looks very nice and clean to me, great work @troglobit.

**Comment by troglobit** [comment]
> ChangeLog looks very nice and clean to me, great work @troglobit.

Thank you for having a look!

**Comment by ivalery111** [comment]
I started working on this, but I am far from your quality, awesome work.

Yet another point to learn something new:)

IMHO, it looks good. Thank you, @troglobit !

**Comment by troglobit** [comment]
> I started working on this, but I am far from your quality, awesome work.
> 
> Yet another point to learn something new:)
> 
> IMHO, it looks good. Thank you, @troglobit !


Thank you so much! 😃👍

**Comment by troglobit** [comment]
OK. I'll do some manual tests on FreeBSD, msys2, and macOS tomorrow.  Unless I find any issues, I'll cut the release tomorrow or Monday 😎

**Comment by troglobit** [comment]
Lots of work done today to clean up API doc generation, unit test integration with TAP format in autotools, automated devcontainer builds, and more ... we're sort of ready for release.

Only really annoying thing is this build issues with msys2 we seem to still have.  It just doesn't work, and I'm so out of touch with Windows these days it's almost scary.  Oh well, maybe someone can have a look at that later.  I'll make a note of it in the ChangeLog at least.

**Comment by beni-sandu** [comment]
I can try to set up a Windows VM and have a look, but I am travelling this week with only a crappy laptop with me, so it might take a bit.

**Comment by troglobit** [comment]
> I can try to set up a Windows VM and have a look, but I am travelling this week with only a crappy laptop with me, so it might take a bit.

That would be really appreciated, but now rush, the v1.3 release will go out tonight (CET) regardless.  Thanks! <3

**Comment by troglobit** [comment]
As promised, finally, here is libnet v1.3 :sunglasses: 

https://github.com/libnet/libnet/releases/tag/v1.3

**Comment by ivalery111** [comment]
> As promised, finally, here is libnet v1.3 :sunglasses: 
> 
> 
> 
> https://github.com/libnet/libnet/releases/tag/v1.3

Thank you a lot!
