### ISSUE TITLE
FreeBSD 13 and latest libnet 1.2 compilation

### ISSUE THREAD

**Issue by UlasSAYGINIM** [libnet/libnet#133]
Hi, is there any change to compile latest version without problem?
any one tried on freebsd? on port system there is old version and on github someone said even after compilation libnet was not working properly.

anyone able to compile and run on freebsd or able to test?
any documentation is also welcome.

thanks.

**Comment by troglobit** [comment]
I was a bit involved in that release, but I did not have time to test on any of the *BSDs, unfortunately.

**Comment by UlasSAYGINIM** [comment]
thank you for your response. can you help to find way to test the library? if you can give information about it. i may try if i can. i really love to update it to latest version because i want to install other ports to use which needs libnet. 
if you can describe , how i can build and than test the functionalities. i may help.

**Comment by UlasSAYGINIM** [comment]
i mean freebsd needs some patching or other technical things like for some ports. i need this kind of tips to make libnet work great on freebsd.

**Comment by troglobit** [comment]
I'm sorry, there is no other documentation currently than https://codedocs.xyz/libnet/libnet/, which is already linked to from the fron page of this project.  I had plans to add a few test cases ease porting, but I have not got around to it.  For now, I recommend testing it with programs such as [Nemesis](https://github.com/libnet/nemesis) which are known to work well with the latest libnet version.

**Comment by UlasSAYGINIM** [comment]
thank you this is helping. when you may have time to easing porting with tests?

**Comment by troglobit** [comment]
That's quite impossible for me to say, work on the Open Source projects I'm involved in doesn't follow a schedule, nor am I paid to work on it.

**Comment by troglobit** [comment]
Latest master, for the upcoming v1.3, builds fine on FreeBSD 13.  I've just recently fixed the CI workflow, see https://github.com/libnet/libnet/blob/master/.github/workflows/build-freebsd.yml for details.

**Comment by UlasSAYGINIM** [comment]
this is wonderful news! thank you very much! glad to you have time to do it.
