### ISSUE TITLE
Fix PF_PACKET detection on musl libc

### ISSUE THREAD

**Issue by herveboisse** [libnet/libnet#157]
Currently, on Linux systems using the musl libc, libnet uses `SOCK_PACKET` sockets for link level operations.
This can be seen in the kernel log:
```
[  127.052413] arping uses obsolete (PF_INET,SOCK_PACKET)
```

These kind of sockets are obsolete and should not be used anymore, `PF_PACKET` sockets should be used instead.

There is a build-time test implemented in `AC_LIBNET_CHECK_PF_PACKET` macro to check if `PF_PACKET` is supported and if not, fallback on `SOCK_PACKET` sockets.

But, the program compiled for the test uses macros to check glibc version to include necessary headers:
```c
#if __GLIBC__ >= 2 && __GLIBC_MINOR >= 1
#include <netpacket/packet.h>
#include <net/ethernet.h>     /* the L2 protocols */
#else
```

Since musl has no FTM (Feature Test Macro) [1], the headers are not included which makes the compilation of the test program fail and finally `AC_LIBNET_CHECK_PF_PACKET` concludes that `PF_PACKET` is not supported.

While I was figuring on how to fix that, I realized this fact: according to `packet(7)` [2], support for `PF_PACKET` sockets was added in Linux 2.2, which was released in January 1999 [3].
This was 24 years ago, so I think it is a reasonable choice to just drop support for `SOCK_PACKET` sockets and assume `PF_PACKET` sockets are always available on any Linux system.

[1] https://wiki.musl-libc.org/faq.html
[2] https://man7.org/linux/man-pages/man7/packet.7.html
[3] https://lkml.iu.edu/hypermail/linux/kernel/9901.2/1084.html

**Comment by troglobit** [comment]
I must say this is probably the best issue report I've ever read on GitHub, and I fully concur.
