### ISSUE TITLE
libnet_name2addr needs root access?

### ISSUE THREAD

**Issue by awisse** [libnet/libnet#162]
[libnet_resolve.c](https://github.com/libnet/libnet/blob/master/src/libnet_resolve.c). `libnet_name2addr4` and `libnet_name2addr6` need a `libnet_t` context just to log an error message. The context is not required for the operation of the function. This is unfortunate as these functions could be useful to an non privileged user . I propose to suppress the `libnet_t` parameter and handle error reporting otherwise, or to modify `libnet_init` to accept a parameter for the creation of a special type of `libnet_t` context by a non privileged user.

**Comment by troglobit** [comment]
We cannot suppress/drop the libnet_t argument to the function, that would break all existing applications that use libnet.  We can however add a new APIs that these functions use, and those new APIs can be made with only the requried arguments.

**Comment by awisse** [comment]
Makes sense. Anyway, there are other, non libnet functions to obtain the binary address from the dot notation of from a hostname (`inet_aton`, `getaddrinfo`), it is not necessary to use `libnet_name2addr4*.
