### ISSUE TITLE
Most man pages missing from dist tarball

### ISSUE THREAD

**Issue by thesamesam** [libnet/libnet#169]
Noticed this after a downstream report at https://bugs.gentoo.org/916025.

```
$ tar tvf /var/cache/distfiles/libnet-1.3.tar.gz | grep -i man
drwxr-xr-x 1001/127          0 2023-10-02 17:49 libnet-1.3/doc/man/
drwxr-xr-x 1001/127          0 2023-10-02 17:49 libnet-1.3/doc/man/man1/
-rw-r--r-- 1001/127       1068 2023-10-02 17:48 libnet-1.3/doc/man/man1/libnet-config.1
-rw-r--r-- 1001/127       3222 2023-10-02 17:48 libnet-1.3/doc/fixmanpages.in
````

It looks like the library manpages are missing from the release tarball. I tried naively adding `--enable-doxygen-man` to `DISTCHECK_CONFIGURE_FLAGS` in Makefile.am but it doesn't seem to do the job yet..

**Comment by troglobit** [comment]
Thank you for taking the time to report this.

**Comment by troglobit** [comment]
I've checked this now.  Not a bug.

Documentation is generated at build time with doxygen, including most of the man pages. From a clean build of the downloaded 1.3 tarball:

```
~/tmp/libnet-1.3$ ls -R doc/
doc/:
...
doc/man:
man1  man3

doc/man/man1:
libnet-config.1

doc/man/man3:
libnet.3  libnet-functions.3  libnet-macros.3
```

**Comment by thesamesam** [comment]
Right, I was hoping the dist tarball could include them pre-generated if that's something you could consider.

https://github.com/libnet/libnet/blob/master/Makefile.am#L31 made me think that was the intention, as it's common for dist tarballs to have them in there.

**Comment by troglobit** [comment]
No. We don't do it for the HTML docs, and I'm pretty sure we didn't in the previous releases either. Anything generated from the source should not be included, with the exception of build related files like configure.

**Comment by thesamesam** [comment]
The intention in https://github.com/libnet/libnet/commit/8dc36788e7bde7f225ed9f0bd8e6472be0e839a6 does seem to have been to provide the man pages in the dist tarball (which many other projects do); indeed the automake manual mentions it at https://www.gnu.org/software/automake/manual/html_node/Man-Pages.html.

But if that is your position now, while I wish it was different, I'll leave the matter there. Thanks.

**Comment by troglobit** [comment]
Now you've put me on the spot ... that does indeed seem to have been the intention.  Well, things change and over time so do ambitions.  I have very little time to spend on OSS these days and iirc, a lot of changes to the build system had to be reverted late in the release process just to fix build issues like parallel build and consistency issues found by make distcheck.  Anything in software can be fixed and tweaked to be made better.  If you want this feature back you can whip up a PR to restore it for the next release.
