### ISSUE TITLE
where libnet_build_icmpv6_router_advertisement and  libnet_build_icmpv6_prefix function

### ISSUE THREAD

**Issue by junwushi** [libnet/libnet#171]
The same sample on the Internet has the above two functions, but it can't be found in libnet 1.3. Why, it has a new libnet? Not here?

**Comment by troglobit** [comment]
I'd like to see where you've found these functions on the Internet?  I've searched but cannot find any reference anywhere.

It's definitely possible someone has extended libnet without upstreaming it back to us, but we're more than happy to take patches, so please let us know.

**Comment by junwushi** [comment]
It comes from chatgpt and provides example code for ICMPv6 routing announcement.

**Comment by troglobit** [comment]
Not sure how to reply to this.  ChatGPT is a great service, I use it myself, but you cannot trust what it says -- it is very good at lying.  If this APIs had existed, they would very likely have been named this way, but we do not have them.  I should know, I'm the maintainer.

![053014_Gullibility_Blog_header](https://github.com/user-attachments/assets/dcf343f1-bcb6-4bf4-8f6e-713b19a2b345)
