### ISSUE TITLE
ping_of_death.c:72]: (style) Suspicious condition

### ISSUE THREAD

**Issue by dcb314** [libnet/libnet#77]
ping_of_death.c:72]: (style) Suspicious condition (assignment + comparison); Clarify expression with parentheses.

Source code is

    if (argc != 2 || ((target = libnet_name2addr4(l, argv[1], LIBNET_RESOLVE) == -1)))

Maybe better source code

    if (argc != 2 || ((target = libnet_name2addr4(l, argv[1], LIBNET_RESOLVE)) == -1))

**Comment by sam-github** [comment]
could you PR  that? It does look better!

**Comment by dcb314** [comment]
I don't understand your comment. Please feel free to fix it.

**Comment by sam-github** [comment]
I think you have found a bug in the example code. I don't have time to fix it. You can clone this repo, fix it, and I will accept the fix, or perhaps some other collaborator has the time.

How to make a PR: https://help.github.com/articles/creating-a-pull-request/

**Comment by dcb314** [comment]
Perhaps I've been slightly less than clear. I've found a bug in this code.

I just find them, I don't fix them. I leave that to other folks who have more knowledge
of the project.

**Comment by sam-github** [comment]
I have every confidence you could fix it if you wanted it fixed, because you included the fix in the issue description. If you don't want to, that's OK, I don't blame you, I don't have the time or interest in fixing it either.

**Comment by sgeto** [comment]
@sam-github 
Hi
My fork is currently a bit of a mess. Do you mind if I push this patch directly to master (so no PR for this. I would clone, edit and push)?
