### ISSUE TITLE
BSD compatible source & bad interface enumeration

### ISSUE THREAD

**Issue by dohnuts** [libnet/libnet#79]
OpenBSD has a downstream patch :
```
--- src/libnet_link_bpf.c.orig  Wed Jan 28 20:45:00 2004
+++ src/libnet_link_bpf.c       Thu Dec  5 19:25:50 2013
@@ -28,7 +28,6 @@
  */

 #include <sys/param.h>  /* optionally get BSD define */
-#include <sys/timeb.h>
 #include <sys/file.h>
 #include <sys/ioctl.h>

@@ -43,6 +42,7 @@
 #include <sys/sysctl.h>
 #include <net/route.h>
 #include <net/if_dl.h>
+#include <net/if_types.h>
 #include "../include/gnuc.h"
 #include "../include/bpf.h"

@@ -308,9 +308,13 @@ libnet_get_hwaddr(libnet_t *l)
     for (next = buf ; next < end ; next += ifm->ifm_msglen)
     {
         ifm = (struct if_msghdr *)next;
+        if (ifm->ifm_version != RTM_VERSION)
+            continue;
         if (ifm->ifm_type == RTM_IFINFO)
         {
             sdl = (struct sockaddr_dl *)(ifm + 1);
+            if (sdl->sdl_type != IFT_ETHER)
+                continue;
             if (strncmp(&sdl->sdl_data[0], l->device, sdl->sdl_nlen) == 0)
             {
                 if (!(ea = malloc(sizeof(struct libnet_ether_addr))))

```

Moreover if you have a bunch of interface , if you ifconfig down one of them the libnet will fail to find a compatible interface.

I guess that just like non ethernet interface were not ignored , down interface are not handled well either

this is true on : 1.1.2.1 , i did not find any path/or issue mentioning that, but i m not very good at github digging.

I will try to upgrade the basic source of the package here and see if the down interface problem still exists, i hope you can accept patches so i  will not have downstream patch here.

**Comment by sam-github** [comment]
yes, we accept patches

**Comment by dohnuts** [comment]
Hello Sam, you can check my fork i did some work on libnet/src/libnet_if_addr.c , this fixes my issues.
The current code completely breaks when iterating a down interface .

The previous patch remove any sprintf reference in the code .

I Need a someone to cross test this on Linux especially, i m running test on various OpenBSD.

Do you have unit test script ? any remarks to get this approved ?

**Comment by sgeto** [comment]
Your fork builds just fine on my Linux box.
Can you submit a pull request?

**Comment by dohnuts** [comment]
Thank you sgeto !
I will need to remove the debug printf before merging back.
( and read how to merge the fork back )

**Comment by sgeto** [comment]
:+1

**Comment by dohnuts** [comment]
#81 is up

**Comment by troglobit** [comment]
Merged to master, with some minor fuzz to commit message. Thank you @dohnuts for taking the time to both report and fix this, and also to everyone involved in the audit! :smiley::+1:
