### ISSUE TITLE
Move libnet to a github organization

### ISSUE THREAD

**Issue by sam-github** [libnet/libnet#83]
I'd like to move libnet to a github organization, to ease collaboration and get it out of my personal github account.

The obvious org name is `libnet`, but it used at the moment. I've asked the maintainer if they will donate it to use: https://github.com/libnet/try_git/issues/1

If not, then we'll need another free organization name, and I'd like to have suggestions, though maybe not until I've had a response from @libnet

For now, this issue is a heads up of what I'm trying to do.

**Comment by dohnuts** [comment]
I wonder if github.com can remove this inactive / squatting account ?

super original : libnet2 ...

**Comment by dohnuts** [comment]
@sam-github any news ?

**Comment by sam-github** [comment]
No response.

Given that libnet is packaged as `libnet1` on debian/ubuntu, maybe use that? or `libnet-pf` for "libnet portable framework"?

**Comment by sam-github** [comment]
I contacted github support to ask them about their policy for dormant github user accounts. I don't want any drama, but if github feels the account should be released, I'd be happy to have it.

**Comment by sgeto** [comment]
or call it just "net" given that this is the name of the library/output
file minus that mandatory prefix.

Or we could go with zlib's approach of moving the prefix to the end. So
"netlib".

**Comment by libnet** [comment]
My account isn’t dormant, but I’m happy to have them rename it if you need the name.  There are some  private repositories shared with me that need to stay private when they do that.

 

Let me know what you need me to do,

Libby Netland McCord

**Comment by sam-github** [comment]
https://github.com/net doesn't work as an org on github, and there is already a well-known netlib: https://www.netlib.org/

@libnet https://help.github.com/en/articles/changing-your-github-username is how to change your username, you can do it yourself -- then pls comment here so I can move this libnet into its place before someone else grabs it! ;-)

And I really appreciate your donating it.

**Comment by sam-github** [comment]
Oh, and @libnet the private repos shared with you remain private, and remain shared.

**Comment by sam-github** [comment]
So, I did the first steps, I created an org called https://github.com/libnet1 and moved this repo to it. If @libnet makes their account name available, I'll rename the org, and we'll be set. If not, we can stay with this org name.

**Comment by libnet** [comment]
okie dok... just got home and will do this now.
Libby

**Comment by sam-github** [comment]
We are at https://github.com/libnet, thanks so much to @lmccord

**Comment by troglobit** [comment]
Thank you so much for this, @lmccord <3
