### ISSUE TITLE
Motion to remove win32/wpdpack from GIT + dist

### ISSUE THREAD

**Issue by troglobit** [libnet/libnet#93]
When merging #65 we got `win32/wpdpack` into the repo, which was also included in the v1.2 release.  I'd propose removing this binary library from libnet and perhaps look at making, e.g., https://nmap.org/npcap/ a requirement for the Windows port.

I don't have any working Windows build environment, so removing `win32/wpdpack` will cause the Windows port to stop working.

**Comment by sam-github** [comment]
Speaking of having a mixture of licenses in a project from #85 ,  libnet appears to be redistributing wpdpack in violation of its license: https://github.com/libnet/libnet/blob/master/win32/wpdpack/license.txt#L6-L16

The advertising clause would require the license be mentioned in libnet's top-level license or README, and of course its GPL incompatible.

Best to remove. Its OK to have a build dep, it would have to be pulled in for windows builds.

**Comment by troglobit** [comment]
Agreed, I'll remove it in a few hours and update the build instructions in README.win32

**Comment by troglobit** [comment]
There, fixed.  The Appveyor CI build is still happy.
